name: Build

on: 
  workflow_dispatch:
  push:
    branches:
        - main
        
env:
    DOTNET_VERSION: "8.x"

jobs:
    build:
        runs-on: ubuntu-latest

        defaults:
            run:
                working-directory: DevHabbit
        
        steps:
            - uses: actions/checkout@v4

            - name: Setup .NET
              uses: actions/setup-dotnet@v4
              with:
                dotnet-version: ${{env.DOTNET_VERSION}}
            
            - name: Restore
              run: dotnet restore DevHabbit.sln

            - name: Build
              run: dotnet build DevHabbit.sln --configuration Release

            - name: Test
              run: dotnet test DevHabbit.sln --configuration Release --no-restore --no-build

            - name: Publish
              run: dotnet publish DevHabbit.sln --configuration Release --no-restore --no-build